import SharedWarehouseScreen from "./SharedWarehouseScreen";
import SharedOrderManagementScreen from "./SharedOrderManagementScreen";
import SharedPrimarySalesScreen from "./SharedPrimarySalesScreen";
import SharedSecondarySalesScreen from "./SharedSecondarySalesScreen";
import SharedTertiarySalesScreen from "./SharedTertiarySalesScreen";
import SharedDistributorScreen from "./SharedDistributorScreen";
import SharedSuperStockListScreen from "./SharedSuperStockListScreen";
import SharedBestPlanScreen from "./SharedBestPlanScreen";
import SharedWholesalerScreen from "./SharedWholesalerScreen";
import SharedDealerScreen from "./SharedDealerScreen";
import SharedRetailerScreen from "./SharedRetailerScreen";
import SharedModernTradeScreen from "./SharedModernTradeScreen";
import SharedChannelMgmtScreen from "./SharedChannelMgmtScreen";
import SharedSfaDmsScreen from "./SharedSfaDmsScreen";
import SharedTradePromotionScreen from "./SharedTradePromotionScreen";
import SharedClaimScreen from "./SharedClaimScreen";
import SharedCollectionScreen from "./SharedCollectionScreen";
import SharedFinanceAccountsScreen from "./SharedFinanceAccountsScreen";
import SharedTransportDispatchScreen from "./SharedTransportDispatchScreen";
import SharedAIAnalyticsScreen from "./SharedAIAnalyticsScreen";
import SharedSettingsUsersScreen from "./SharedSettingsUsersScreen";

export const WarehouseScreen = SharedWarehouseScreen;
export const OrderManagementScreen = SharedOrderManagementScreen;
export const PrimarySalesScreen = SharedPrimarySalesScreen;
export const SecondarySalesScreen = SharedSecondarySalesScreen;
export const TertiarySalesScreen = SharedTertiarySalesScreen;
export const DistributorScreen = SharedDistributorScreen;
export const SuperStockListScreen = SharedSuperStockListScreen;
export const BestPlanScreen = SharedBestPlanScreen;
export const WholesalerScreen = SharedWholesalerScreen;
export const DealerScreen = SharedDealerScreen;
export const RetailerScreen = SharedRetailerScreen;
export const ModernTradeScreen = SharedModernTradeScreen;
export const ChannelMgmtScreen = SharedChannelMgmtScreen;
export const SfaDmsScreen = SharedSfaDmsScreen;
export const TradePromotionScreen = SharedTradePromotionScreen;
export const ClaimScreen = SharedClaimScreen;
export const CollectionScreen = SharedCollectionScreen;
export const FinanceAccountsScreen = SharedFinanceAccountsScreen;
export const TransportDispatchScreen = SharedTransportDispatchScreen;
export const AIAnalyticsScreen = SharedAIAnalyticsScreen;
export const SettingsUsersScreen = SharedSettingsUsersScreen;
